defenseunicorns/zarf-package-software-factory

Makefile
README.md
manifests/.gitignore
manifests/atlassian/atlassian-manifests.yaml
manifests/bigbang/bigbang-manifests.yaml
manifests/flux/flux-manifests.yaml
manifests/jenkins/jenkins-manifests.yaml
template/bigbang/kustomization.yaml
template/bigbang/values.yaml
template/flux/kustomization.yaml
zarf.yaml

Copied from https://github.com/defenseunicorns/zarf/tree/12460b2be7054c1fa71f95c39223611ae313a455/examples/software-factory

Initial code

---

doc/adr/0001-gitlab-as-sso-provider-but-without-cac-support.md
doc/adr/0001-tbd-as-sso-provider.md

Fixes #23 
The discerning reader will discover that... The decision hasn't been made yet! The Context section applies to both, so I wrote that, and left "TBD" in Decision and Consequences.
I propose we use the discussion here to make the decision, then I'll update the document once the decision is made and get it merged.

ADR on SSO Provider

---

doc/sso.md

Docs for Confluence manual SSO config

---

kustomizations/softwarefactoryaddons/jira/values.yaml

Implements #90  Adds a persistent volume claim to allow for pod restarts without reconfiguration. Using local-path for demo storage class.

Add jira persistence

---

kustomizations/bigbang/common/values.yaml

Adds the Gitlab docker registry to the public gateway

Add GitLab docker registry to the public gateway

---

doc/sso.md

Update Jira SSO configuration docs

---

doc/disable-postgres-operator-and-minio.md

Write doc for disabling Postgres Operator and MinIO if the user is choosing to use external services.

Doc for disabling Postgres Operator and MinIO

---

doc/configure-jira-to-use-an-external-database.md

Document how to configure Jira to use an external database

---

.pre-commit-config.yaml
test/e2e/e2e_basic_smoke_test.go
test/e2e/utils/utils.go
zarf.yaml

Adding flux-cli to zarf.yaml

---

kustomizations/bigbang/common/values.yaml
kustomizations/bigbang/kustomization.yaml
kustomizations/softwarefactoryaddons-deps/base/gitrepository.yaml
kustomizations/softwarefactoryaddons/base/gitrepository.yaml
manifests/setup.yaml

Add the "zarf-ified" URLs back due to [this issue](https://github.com/defenseunicorns/zarf/issues/564)

Add "zarf-ified" URLs back

---

kustomizations/softwarefactoryaddons/base/gitrepository.yaml
kustomizations/softwarefactoryaddons/jenkins/common-values.yaml
kustomizations/softwarefactoryaddons/jira/values.yaml
renovate.json5
zarf.yaml

Update Jenkins and plugins

---

doc/configure-gitlab-to-use-an-external-database-and-s3-buckets.md

Add docs for telling GitLab to use an external database

---

kustomizations/softwarefactoryaddons/confluence/common-values.yaml

- Turn off collaborative editing
- Add resourse requests and limits
Closes #88

Confluence stability updates

---

Makefile
flux/zarf.yaml
kustomizations/bigbang/vendor/bigbang/base/gitrepository.yaml
zarf.yaml

Update Big Bang and Jenkins helm chart

---

test/tf/public-ec2-instance/main.tf

Add a CreatedBy tag to identify the caller creating the test runner

---

kustomizations/bigbang/common/values.yaml

to resolve intemittent startup issues that were experienced at the old level

Increase Minio memory request and limit

---

.github/workflows/test-command.yml
Makefile

Run E2E tests in main

---

.github/workflows/test-command.yml

Send slack msg on pipeline failure in main

---

.pre-commit-config.yaml
Makefile
day2/zarf.yaml
flux/zarf.yaml
zarf.yaml

Upgrade Zarf version to v0.24.0-rc3

---

kustomizations/bigbang/common/values-bigbang.yaml
kustomizations/bigbang/environment-bb/values-bigbang.enc.yaml

Fix loki not being able to send logs to minio

---

backup-and-restore/confluence/README.md
backup-and-restore/confluence/files/pod.yaml
backup-and-restore/confluence/zarf.yaml
backup-and-restore/jira/files/pod.yaml
backup-and-restore/jira/zarf.yaml
kustomizations/softwarefactoryaddons/base/databases/confluence.yaml
kustomizations/softwarefactoryaddons/base/databases/jira.yaml
kustomizations/softwarefactoryaddons/base/helmrelease.yaml
kustomizations/softwarefactoryaddons/base/kustomization.yaml
kustomizations/softwarefactoryaddons/base/pvcs/confluence-shared-home-single-node.yaml
kustomizations/softwarefactoryaddons/base/pvcs/jira-shared-home-single-node.yaml
kustomizations/softwarefactoryaddons/confluence/common-values.yaml
kustomizations/softwarefactoryaddons/jira/values.yaml
kustomizations/softwarefactoryaddons/postgres-db/postgres-db-minio-creds.env.enc

Backup and Restore for Confluence

---

kustomizations/softwarefactoryaddons/artifactory/common-values.yaml
kustomizations/softwarefactoryaddons/base/gitrepository.yaml
kustomizations/softwarefactoryaddons/base/helmrelease.yaml
manifests/setup.yaml
zarf.yaml

Updated to the latest Artifactory version in bigbang packages.
Updated to use ironbank images.
Closes https://github.com/defenseunicorns/zarf-package-software-factory/issues/257

Update Artifactory Version and Images

---

backup-and-restore/artifactory/README.md
backup-and-restore/artifactory/files/pod.yaml
backup-and-restore/artifactory/zarf.yaml
backup-and-restore/confluence/zarf.yaml
backup-and-restore/jira/zarf.yaml
kustomizations/softwarefactoryaddons/base/databases/artifactory.yaml

also added some retries for minio related stuff to jira and confluence backup/restore as it seems kinda flakey
closes #608

Artifactory backup and restore

---

Makefile
flux/zarf.yaml
kustomizations/bigbang/common/values-bigbang.yaml
kustomizations/bigbang/common/values-minio-git-repo.yaml
kustomizations/bigbang/vendor/bigbang/base/gitrepository.yaml
kustomizations/softwarefactoryaddons/jira/values.yaml
manifests/setup.yaml
zarf.yaml

Closes https://github.com/defenseunicorns/zarf-package-software-factory/issues/610

Upgrade bigbang to 1.57.1

---

kustomizations/gitlab-redis/base/gitrepository.yaml
kustomizations/gitlab-redis/redis-config/values.yaml
zarf.yaml

Closes https://github.com/defenseunicorns/zarf-package-software-factory/issues/627

Update redis to latest bb version

---

kustomizations/softwarefactoryaddons/base/gitrepository.yaml
kustomizations/softwarefactoryaddons/base/helmrelease.yaml
kustomizations/softwarefactoryaddons/jenkins/common-values.yaml
zarf.yaml

Updated Jenkins to use the bigbang chart. This is also an overall newer version of Jenkins.
Closes https://github.com/defenseunicorns/zarf-package-software-factory/issues/628

Update Jenkins Version and Chart

---

backup-and-restore/jira/zarf.yaml
kustomizations/softwarefactoryaddons/base/gitrepository.yaml
zarf.yaml

Ignore the branch name. Doing the others in separate branches.
Closes https://github.com/defenseunicorns/zarf-package-software-factory/issues/626

Update Jira Version

---

.pre-commit-config.yaml
Makefile
backup-and-restore/artifactory/zarf.yaml
backup-and-restore/confluence/zarf.yaml
backup-and-restore/gitlab/zarf.yaml
backup-and-restore/jenkins/zarf.yaml
backup-and-restore/jira/zarf.yaml
day2/zarf.yaml
flux/zarf.yaml
zarf.yaml

Update zarf to version 0.26.3

---

kustomizations/bigbang/common/values-bigbang.yaml

Up mem and cpu limit for prometheus to keep from being oom killed

---

zarf.yaml

Update Zarf Package with tag refs

---

backup-and-restore/artifactory/zarf.yaml
backup-and-restore/confluence/zarf.yaml
backup-and-restore/gitlab/zarf.yaml
backup-and-restore/jenkins/zarf.yaml
backup-and-restore/jira/zarf.yaml
day2/zarf.yaml
flux/zarf.yaml
kustomizations/bigbang/istio-updates/sonarqube-istio-updates.yaml
zarf.yaml

Added a peerauth port exception for sonarqube and updated the zarf variables to use the correct tmpl syntax.

Sonarqube and zarf var updates
